# Generated by Django 5.2.8 on 2026-02-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_data_event_date_event_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Music', 'Music'), ('Foods', 'Foods'), ('Movies', 'Movies'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
