# Generated by Django 4.2.10 on 2026-02-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Music', 'Music'), ('Foods', 'Foods'), ('Movies', 'Movies'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
