# Generated by Django 4.2.10 on 2026-02-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Music', 'Music'), ('Food', 'Food'), ('Art', 'Art'), ('Movies', 'Movies'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_category',
            field=models.CharField(blank=True, help_text="Specify category if 'Other' is selected", max_length=100, null=True),
        ),
    ]
