# Generated by Django 4.2.10 on 2026-02-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_bio_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
